use form_with, requre email
mikker/passwordless pull request #128
Opened 2022-11-08 12:08 UTC by yshmarov

* form_with allows more options than form_for, it's easyer to style.
* don't let the html form submit null email

2022-11-14 08:47 UTC, mikker commented
Hey @yshmarov! Thank you for all these. Looks like decent additions.

How does `form_with` benefit styling? I imagine it'll add more or perhaps different ids and classes? Is this potentially a (very subtly and harmlessly) breaking change?

I can definitely see how it's nice to share translations however I fear bundling them in the gem will make it very hard to do updates as we'd have to wait for all translations to be ready before we can do breaking changes, etc... So maybe we can put the translations in the wiki here on GH instead?

It breaks my heart what's being done to your country and people. Rooting for you 💛💙

2022-11-22 13:03 UTC, yshmarov commented
Thanks for your reply & support @mikker !

`form_with` is supposed to unify `form_for` and `form_tag`, that seem to be slowly going obsolete https://github.com/rails/rails/pull/26976

> How does form_with benefit styling?

you don't have to apply `id`, `data`, `class` inside html_options
```
<%= form_with model: @post, id: “custom-id”, class: “custom-class” do |form| %>
<%= form_for @post, html: { id: “custom-id”, class: “custom-class” } do |form| %>
```

> Is this potentially a (very subtly and harmlessly) breaking change?

I don't think so...

> I can definitely see how it's nice to share translations however I fear bundling them in the gem will make it very hard to do updates as we'd have to wait for all translations to be ready before we can do breaking changes, etc... So maybe we can put the translations in the wiki here on GH instead?

Good point! You are right!

2022-11-29 12:36 UTC, mikker requested changes
- [ ] Move translation to GH wiki
- [x] Add item to changelog

2022-11-30 00:10 UTC, yshmarov commented
@mikker I don't see the Wiki tab available on the repo. It might be disabled?

2022-11-30 08:58 UTC, mikker commented
Perfect 👌
I think the wiki is there now. I've created the first page.

2022-11-30 09:01 UTC, mikker approved these changes
❤️🧡💛💚💙💜

2022-11-30 09:01 UTC, mikker commented on CHANGELOG.md
> +- Added frontend validation for email presence in views
```suggestion
- Replaced `form_for` with `form_with` in view template ([#128](https://github.com/mikker/passwordless/pull/128))
- Added frontend validation for email presence in views ([#128](https://github.com/mikker/passwordless/pull/128))
```

2022-11-30 09:03 UTC, merged

2022-11-30 21:05 UTC, yshmarov commented
@mikker looks like the wiki is not community-editable 🙃 
<img width="987" alt="Screenshot 2022-11-30 at 22 04 17" src="https://user-images.githubusercontent.com/13472945/204907731-80e07892-08bf-4b91-a7fc-eae95e73e62d.png">

2022-12-01 17:31 UTC, mikker commented
Sorry, try again!