Add passwordless test helpers
mikker/passwordless pull request #90
Opened 2020-10-28 14:55 UTC by rickychilcott

This is a PR to add test helpers for test unit and rspec. I tried this locally on a project I'm using and it works ok, but I'm only using rspec. Someone who has a good example test unit project should try this or some tests can be integrated into a passwordless example app.

This takes a lot of code and ideas from #71 so no credit is taken here, just trying to pull together to get to this as part of a 1.0 release (#89).

Close #71 and address #29

2020-10-29 08:08 UTC, mikker requested changes
Thank you for this @rickychilcott!

They'll have to be modified a bit for 1.0 but that doesn't mean they aren't a great addition. A few remarks and suggestions, otherwise looks great!

2020-10-29 08:08 UTC, mikker commented on README.md
> +* [Testing](#testing)
```suggestion
* [Test helpers](#testing)
```

2020-10-29 08:08 UTC, mikker commented on README.md
> +## Testing
```suggestion
## Test helpers
```

2020-10-29 08:08 UTC, mikker commented on README.md
> +To test controller that are protected by a `before_action :require_user`, require Passwordless's test helpers in your test suite.
```suggestion
To help with testing, a set of test helpers are provided.
```

2020-10-29 08:08 UTC, mikker commented on README.md
> +For `rspec`, add the following line to your `spec/rails_helper.rb` or
```suggestion
If you are using RSpec, add the following line to your `spec/rails_helper.rb` or
```

2020-10-29 08:08 UTC, mikker commented on README.md
> +`spec/spec_helper` if `rails_helper` does not exist:
```suggestion
`spec/spec_helper.rb` if `rails_helper` does not exist:
```

2020-10-29 08:08 UTC, mikker commented on README.md
> +passwordless_sign_in(user) # signs you in as a user
I'm not sure I like this dual meaning API. Let's split it into `passwordless_sign_in(resource)` and `passwordless_sign_in_path`.

2020-11-02 12:27 UTC, rickychilcott commented
Thanks @mikker. I made the requested changes.

I was modeling some of the syntax off of https://github.com/thoughtbot/clearance#controller-test-helpers but I looked too quickly and didn't realize that they effectively shim the `current_user` if you just did a `sign_in` without doing `sign_in_as(user)`, so I dropped my weird overloading of the `passwordless_sign_in`/`passwordless_sign_in(user)` form. 

Let me know if you'd like any other changes.

2020-11-02 12:38 UTC, mikker approved these changes
💙💚💛💜❤️

2020-11-02 12:39 UTC, merged